name: Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tests_linux:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: [3.9]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: python -m pip install -U -r requirements-dev.txt
      - name: Install MyNumPy
        run: |
          python -m pip install -U .
      - name: Run Tests
        run: |
          set -e
          pip check
          pytest test
        shell: bash
